#!/bin/sh

if [ "$BUTTON" = "wlan" -a "$ACTION" = "pressed" ];then
        if [ "$(uci -q get wireless.radio0.disabled)" = "1" ]; then
                uci set wireless.radio0.disabled='0'
                uci set wireless.radio1.disabled='0'
                uci commit wireless
                logger -t "[wireless]" "activating wifi by user button."
                wifi up
        else
                uci set wireless.radio0.disabled='1'
                uci set wireless.radio1.disabled='1'
                uci commit wireless
                logger -t "[wireless]" "deactivating wifi by user button."
                wifi down
        fi
fi